### ISSUE TITLE
Add Prettier code formatter 

### ISSUE THREAD

**Issue by alepop** [LiskHQ/lisky#172]
We need add [prettier](https://github.com/prettier/prettier) ([prettier-eslint](https://github.com/prettier/prettier-eslint)) to `lisky` and to all other `LiskHQ` projects.
Prettier is an opinionated code formatter with support for:
```
JavaScript, including ES2017
JSX
Flow
TypeScript
CSS, LESS, and SCSS
JSON
GraphQL
```

**Comment by willclarktech** [comment]
@alepop Do you know how likely it is that prettier would introduce a style change which contravenes our eslint rules, but which `eslint --fix` wouldn't fix?

**Comment by willclarktech** [comment]
Prettier has been added to lisk-js, so we'll see how well it works there before adding it in Lisky.

**Comment by willclarktech** [comment]
This was already added in #369
