### ISSUE TITLE
Add license information to interactive mode introduction

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisky#200]
https://github.com/LiskHQ/lisk-js/blob/master/LICENSE#L652

**Comment by mpuk** [comment]
@willclarktech Can I do this ?

**Comment by mpuk** [comment]
@willclarktech Can I do this ?

**Comment by willclarktech** [comment]
Hi @mpuk, thanks for the offer, but we've got to make sure we're using the correct wording etc, so we'll do this one ourselves.
