### ISSUE TITLE
Update .npmignore

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisky#257]
We have several new files in the root directory that don't need to be included in the published package.

**Comment by mpuk** [comment]
@willclarktech Can I do this ? Which files do you mean ?

**Comment by willclarktech** [comment]
Hi @mpuk, that would be great!
These files should be added:
```
.nvmrc
.nycrc
.snyk
```

In addition, we've moved away from grunt, so `Gruntfile.js` should be removed.

**Comment by mpuk** [comment]
@willclarktech Understood. I will do it today and make PR around midnight. Thanks.

**Comment by mpuk** [comment]
@willclarktech `Gruntfile.js` is not in branch 0.3.0 which I am based off. Although this file exists in `master`.  So what do you suggest?

**Comment by willclarktech** [comment]
Hi @mpuk, thanks for the PR, but this issue was about updating the `.npmignore` file, not the `.gitignore` file. `.npmignore` specifies files/folders that should not be included when publishing the npm package: https://docs.npmjs.com/misc/developers

This is the relevant file: https://github.com/LiskHQ/lisky/blob/0.3.0/.npmignore

**Comment by mpuk** [comment]
@willclarktech Oh I see. I did not know that npm has it's own ignore file. Can I remake it?

**Comment by willclarktech** [comment]
Sure! FYI, that file is alphabetical with files in the first block and directories in the second.
