### ISSUE TITLE
Make PR branching approach clearer

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisky#265]
In our new CONTRIBUTING file we ask people to branch off master, but a pull request that addresses any issue that's part of a version project should branch off the respective version branch. This should be made clear in our CONTRIBUTING file.

**Comment by mpuk** [comment]
@willclarktech Can I do this ?

**Comment by willclarktech** [comment]
Hi @mpuk, thanks for the offer, but it'll be easiest if we do this ourselves so we can coordinate in-house about wording etc.
