### ISSUE TITLE
Add david-dm badge

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisky#266]
https://david-dm.org/

To keep our dependencies fresh

**Comment by mpuk** [comment]
@willclarktech Hi :) Can I do this issue ?

**Comment by willclarktech** [comment]
Hi @mpuk, that would be great!

Please base off the [0.3.0 branch](https://github.com/LiskHQ/lisky/tree/0.3.0) and submit a PR to that branch. The badges should go into the README.md file in the root of the project next to the other badges, and we should have one for dependencies and one for devDependencies.

**Comment by willclarktech** [comment]
Lines 4–5 here should show you all you need to do: https://raw.githubusercontent.com/alanshaw/david-www/master/README.md
How it looks: https://github.com/alanshaw/david-www/blob/master/README.md

**Comment by mpuk** [comment]
@willclarktech  I am afraid it takes more work than using those 2 lines in raw README.md you posted here.
