### ISSUE TITLE
GWT tests for set command

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisky#287]
Part of #220

**Comment by WilliamStephens** [comment]
Hey! Is it cool if I take a look at this?

**Comment by willclarktech** [comment]
Hi @WilliamStephens, thanks for the offer, but we're still putting in place standards for these tests so probably best if we do it ourselves at this point. Once #220 is complete, I'll tackle #258 which should make it easier for community members to contribute in this respect.

**Comment by WilliamStephens** [comment]
Yea no problem was just trying to knock out my hacktoberfest pr's really quick. Thanks for letting me know before I started on it.
