### ISSUE TITLE
Remove checkReadAccess function from config module

### ISSUE THREAD

**Issue by KyleFromOhio** [LiskHQ/lisky#429]
### Description
Lisky works fine once. Then when try to run a second time errors. I have to delete the ./lisky/config.json for it to work again.

### Steps to Reproduce
`$ lisky (runs fine first time)`

`$ lisky`
~/lisk-test/lib/node_modules/lisky/dist/utils/config.js:82
	var fn = _fs2.default.accessSync.bind(null, path, _fs2.default.constants.R_OK);^
TypeError: Cannot read property 'R_OK' of undefined
    at checkReadAccess (~/lisk-test/lib/node_modules/lisky/dist/utils/config.js:82:74)
    at getConfig (~/lisk-test/lib/node_modules/lisky/dist/utils/config.js:116:2)
    at Object.<anonymous> (~/lisk-test/lib/node_modules/lisky/dist/utils/config.js:121:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (~/lisk-test/lib/node_modules/lisky/dist/index.js:27:15)`

`$ rm ~/.lisky/config.json`
`$ lisky (runs fine again)`

### Versions
Lisk testnet and mainnet
Ubuntu 16.04
Lisky v0.3.0
npm 3.5.2
nodejs v4.2.6

**Comment by willclarktech** [comment]
Hi @KyleFromOhio, thanks for reporting. The officially supported version of Node.js for Lisky v0.3.0 is 6.11.1, and looks like the location of these constants was changed between v4 and v6. If you use Node.js v6 does it work?

By the way we have an undocumented helper command `lisky clean` which will delete your config file for you (in case you end up having to do this a lot).

**Comment by willclarktech** [comment]
Having said that, the documentation for v6 says

> **Note:** Not every constant will be available on every operating system.

So we might need to revisit this even if v6 solves the problem for Kyle.

https://nodejs.org/docs/latest-v6.x/api/fs.html#fs_fs_constants_1

**Comment by Tosch110** [comment]
We can consider to remove `checkReadAccess` and be more optimistic. Handling error cases when they appear but without checking the state the file is in.

**Comment by KyleFromOhio** [comment]
This is just a standard nodejs install on Ubuntu from the default repo. 16.04 i believe is supported until 2021. I could upgrade manually but I think lisky should tell the user their version is too old or something instead of halting abruptly. Or instead of trying to catch all these odd errors maybe a warning message when you run lisky like "Warning: We detected your nodejs version is < 6.11.1+. Please upgrade nodejs.". Something like how homebrew does it.

**Comment by KyleFromOhio** [comment]
The following fixed the error but again standard repo package comes in at v4X...

```
sudo apt-get install -y build-essential
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
sudo apt-get install -y nodejs
nodejs -v
v9.5.0
```

**Comment by willclarktech** [comment]
OK thanks for the information, I've created this follow up issue:https://github.com/LiskHQ/lisky/issues/431

Since the supported Node.js version is 6.11.1, I would not recommend using Node.js version 9.

**Comment by KyleFromOhio** [comment]
in case anyone else sees this then use this instead...
```
sudo apt-get remove -y nodejs
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
nodejs -v
v6.12.3
```

**Comment by willclarktech** [comment]
Superseded by #493
