### ISSUE TITLE
Handle missing keys in config file

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisky#430]
### Description

The configuration for a user might or might not have certain properties. We should be able to handle the existence / absence of keys in a proper way.

### Steps to Reproduce

Reference and follow-up to:
https://github.com/LiskHQ/lisky/pull/417#discussion_r165452408

**Expected behavior:** 

Optimally adding missing keys / inform about deprecated keys. Having a procedure for updates of the config file is preferred without too much premature optimisation.

**Actual behavior:** 

It throws if a key is not existent.

### Versions

0.3.0 to 1.0.0

**Comment by shuse2** [comment]
superseded by #493
