### ISSUE TITLE
Create Configuration error

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisky#462]
### Description

Error messages involving the configuration can get a configuration error

**Expected behavior:** 

When the user makes a mistake involving the configuration file (wanting to set a non-existent property) a Configuration Error should be thrown

**Actual behavior:** 

A Validation Error is thrown

### Versions

1.0.0

### Additional Information

Follow-up https://github.com/LiskHQ/lisky/pull/417#discussion_r166901030

**Comment by willclarktech** [comment]
@Tosch110 I'm actually not convinced this issue is a good idea any more, possibly because the `set` command has been refactored.

**Comment by shuse2** [comment]
If I understand correctly, I think Validation error make sense because the user is sending `invalid` command or value

**Comment by willclarktech** [comment]
Closing unless we need it after https://github.com/LiskHQ/lisky/pull/417
