### ISSUE TITLE
Migration of the config file 0.3 -> 1.0

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisky#493]
### Description

During the update from version 0.3 to the current 1.0-beta the old config in `~/.lisky/config.json` stays the same. Due to differences in the required properties ie. rename `liskJS` to `api`, the behavior of the application can be very confusing for a potential user.

### Steps to Reproduce

1. `npm i -g lisky@0.3`
1. start `lisky`, the config file is created
1. `npm i -g lisky@beta`
1. start `lisky` again
1. type `config`

**Expected behavior:**

```
{
	"name": "lisky",
	"json": false,
	"api": {
		"node": "http://localhost:4000",
		"network": "test"
	},
	"pretty": false
}
```

**Actual behavior:**

Invalid config file is provided to the 1.0 instance:

```
{
	"name": "lisky",
	"json": false,
	"liskJS": {
		"node": "localhost",
		"port": "4000",
                ...
	},
	"pretty": false
}
```

**Reproduces how often:**
always

### Versions

1.0.0-beta.1

**Comment by willclarktech** [comment]
This won't affect the release under the name `lisk-commander` but we should have a proper strategy if the idea is still to release under the name `lisky` with a deprecation notice. Thoughts @shuse2?

**Comment by shuse2** [comment]
I think `README` is sufficient for 1.0, but slightly better solution would be to validate and warn user on start.
